use_frameworks!

target 'MVSegmentedControl_Example' do
  pod 'MVSegmentedControl', :path => '../'

  target 'MVSegmentedControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
